spring:
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  kafka:
    producer:
      acks: all
      batch-size: 32768
      linger-ms: 10

logging:
  level:
    root: WARN
    com.searchengine: INFO